version: '3.7'

services:

  api:
    container_name: adboard-api
    build:
      context: .
      dockerfile: src/Host/AdBoard.Host.Api/Dockerfile
    restart: always
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__PostgresAdBoardDb=Server=postgres;Database=adboard;Username=postgres;Password=jsYg59FwKf7H;Port=5432
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - "postgres"
    networks:
      - adboard-network

  migrator:
    container_name: adboard-migrator
    build:
      context: .
      dockerfile: src/Host/AdBoard.Host.Migrator/Dockerfile
    environment:
      - ConnectionStrings__PostgresAdBoardDb=Server=postgres;Database=adboard;Username=postgres;Password=jsYg59FwKf7H;Port=5432
    networks:
      - adboard-network
    depends_on:
      - "postgres"
    restart: on-failure

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jsYg59FwKf7H
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - adboard-network

  admin:
    image: adminer
    restart: always
    depends_on: 
      - "postgres"
    ports:
      - 8080:8080
    networks:
      - adboard-network

volumes:
  pg-data:

networks:
  adboard-network: