name: Build and push Docker images

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        # Username used to log against the Docker registry
        username: ${{ secrets.dockerUsername }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.dockerPassword }}
    - name: Build and push the API image
      run: docker build -f "src/Host/AdBoard.Host.Api/Dockerfile" . --push -t prostoaleks/adboard-api:latest
    - name: Build and push the Migrator image
      run: docker build -f "src/Host/AdBoard.Host.Migrator/Dockerfile" . --push -t prostoaleks/adboard-migrator:latest
